### ISSUE TITLE
Création des tables DB

### ISSUE THREAD

**Issue by magfUdeS** [loulouX/IFT585-TP3#1]

**Comment by loulouX** [comment]
je n'ai pas fais des triggers pour deux raisons
- je ne m'y connais pas assez
- je trouve cela superflu ce sont des vérifications ou des conditions qui peuvent se faire à même le code .
tout comme cette notion de base de donnée.

**Comment by magfUdeS** [comment]
En effet, pas besoin de trigger pour ce tp

**Comment by magfUdeS** [comment]
Création des tables terminée. 5 tables en tout:
1. files
2. files_by_group
3. groups
4. users
5. users_by_group

**Comment by loulouX** [comment]
je pensais que les tables que j'avais créé ne correspondait pas a ce que tu voulais 
mais je vois bien quelque unes la.
im still in the darkness

**Comment by magfUdeS** [comment]
Il y avait les tables User et Files qui étaient bonnes. Mais j'ai dû refaire la table Files pour changer le type pour introduire les séquences

**Comment by loulouX** [comment]
devront nous aussi utiliser des séquences ? pour le coté client 
bon je vais ouvrir une issue client pour essayer de mettre sur écrit ce qu'il faut faire tu me corrige stp
